### ISSUE TITLE
How to create parameters_best_final.mat

### ISSUE THREAD

**Issue by mdanb** [dgalvis/Senescence_Model#1]
What should I run to create the file `parameters_best_final.mat`? I can't find the code to generate this file

**Comment by dgalvis** [comment]
Hello, I did this all by hand (sorry it was an early coding project for me!). So for example: "parameters_100_best.mat" is just a copy of one of the files parameters_stnum100_it{j}.mat (for j = 1:10). In particular, it is a copy of the file that had the lowest error (cost function evaluation of the final solution). 

I just loaded in each of the ten files to matlab, looked at the one that had the lowest error, copied and renamed it.
