### ISSUE TITLE
Running the model on other cell lines

### ISSUE THREAD

**Issue by hudenise2** [dgalvis/Senescence_Model#2]
Hi, I would like to apply your model to other cell lines than dermal fibroblasts.
Ii is not clear to me if I need to optimise the content of the result_files. If so, it is mentioned to run the data_stuff.m script however it is not provided on the repository.
In absence of this script, I tried to run Run_opts.m using an empty result_files directory however, it seems to run extremely slowly.
Could you advise, please?
In general, would you be able to provide a stepwise description of the best way to apply your model to different cell lines ?
Thanks

**Comment by dgalvis** [comment]
Hello, if comparison_data.mat (as generated by create_data_file.m) has the same format as the example in the repository and you have created an empty directory ./result_files, then Run_opt.m should work. Indeed, the optimisation process is slow because it runs the genetic algorithm function "ga" (a Matlab global optimisation tool) with a big population size and over many iterations.

**Comment by hudenise2** [comment]
Indeed it took a long time run. So the Run_opts.m script has completed.
However the subsequent scripts use the final_best.mat files. According to the response you gave to the closed issue, you selected the file with the lowest error from the stnum100 files to generate parameters_100_best.mat.
I can repeat the procedure you describe for parameters_40_best.mat, parameters_60_best.mat and parameters_150_best.mat. Using the same approach, I can generate the other 22 other '_best' files but then how is the parameters_final_best.mat file generated?
There is no script that I can see that take those as input and generate this file.
Following the logic of the answer to mdanb issues, I thought this was a copy of the file with lowest error among those but it is not the case. How was it generated? This is really missing and it would be very useful to describe it
Thanks

**Comment by dgalvis** [comment]
There are files called " paramaters_final{i}_ga.mat" for i in {1...21}. I believe that parameters_final_best.mat is a copy of one of these files. The one with the lowest error. It has been a long time, but I believe that these are the parameterisations of the full model (all parameters free) on the full datasets (no data points held out).

You should be able to verify this if you want by looking through the files in result_files

I would also like to reiterate that I wrote this repository to analyse the dataset I was working with at the time. It was not designed to be applied to new datasets. Please make sure you fully understand what the code is doing to your data before interpreting the results.
